// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJr7hM1sG9G0xCgDPkfjf9tx7rRP-Q8go',
    appId: '1:925290013704:web:1d1f76b584be29c03f5dbd',
    messagingSenderId: '925290013704',
    projectId: 'tic-tac-toe-d266e',
    authDomain: 'tic-tac-toe-d266e.firebaseapp.com',
    storageBucket: 'tic-tac-toe-d266e.appspot.com',
    measurementId: 'G-C241YXR0NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtBgtymuOzDRg4569QKFJpyJm9rW6yfE',
    appId: '1:925290013704:android:f67ceb062c6bf8133f5dbd',
    messagingSenderId: '925290013704',
    projectId: 'tic-tac-toe-d266e',
    storageBucket: 'tic-tac-toe-d266e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBjRAcZrfxpRhJ0Z4aGEF2Svi1k3mISQ',
    appId: '1:925290013704:ios:280488f36db2826e3f5dbd',
    messagingSenderId: '925290013704',
    projectId: 'tic-tac-toe-d266e',
    storageBucket: 'tic-tac-toe-d266e.appspot.com',
    iosClientId: '925290013704-uu8vuv5f2jov6u02q00mngsjgpi9ir3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBjRAcZrfxpRhJ0Z4aGEF2Svi1k3mISQ',
    appId: '1:925290013704:ios:280488f36db2826e3f5dbd',
    messagingSenderId: '925290013704',
    projectId: 'tic-tac-toe-d266e',
    storageBucket: 'tic-tac-toe-d266e.appspot.com',
    iosClientId: '925290013704-uu8vuv5f2jov6u02q00mngsjgpi9ir3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticTacToe',
  );
}
